version: '3.3'
services:
  postgres_catalogo:
    image: postgres:15
    container_name: postgres_catalogo
    environment:
      POSTGRES_USER: bruno
      POSTGRES_PASSWORD: root
      POSTGRES_DB: catalogodb
    ports:
      - 5451:5432
    volumes:
      - ./postgres:/var/lib/postgresql/data